// Este archivo almacenará las ventas completadas durante la sesión actual.
export let ventasDelDia = [
  {
    id: "VTA-EXAMPLE-01",
    cliente: {
      id: 4,
      nombre: "Pedro",
      alias: "Peter",
      telefonos: [{ tipo: "Móvil", numero: "275-333-4444" }],
      direcciones: [],
    },
    items: [
      {
        productId: "PECH",
        optionId: "PP-PECH",
        optionName: "Pulpa de Pechuga",
        quantity: 0.75,
        cost: 138.75,
        priceType: "publico",
        pricePerKg: 185,
        personalizations: { Procesamientos: ["Milanesa"] },
      },
      {
        productId: "AL",
        optionId: "AL",
        optionName: "Ala",
        quantity: 1.2,
        cost: 110.0,
        priceType: "publico",
        pricePerKg: 100,
        personalizations: { Procesamientos: ["Cortada en 2"] },
        discount: {
          monto: 10.0,
          descripcion: "Descuento por cantidad",
          originalCost: 120.0,
          tipoDescuentoAplicado: "Cantidad",
        },
      },
      {
        productId: "PA",
        optionId: "manual",
        optionName: "Producto Adicional",
        quantity: 1,
        cost: 25.0,
        priceType: null,
        pricePerKg: null,
        personalizations: { descripcion: ["Jitomates"] },
      },
      {
        productId: "ENVIO",
        optionId: "express-chiautla",
        optionName: "D. Express Chiautla",
        quantity: 1,
        cost: 15.0,
        priceType: null,
        pricePerKg: null,
        personalizations: { descripcion: ["$15.00"] },
      },
    ],
    total: 288.75,
    fechaCompletado: new Date(Date.now() - 10 * 60000).toISOString(),
    pagoCon: { 200: 1, 100: 1 },
    cambioEntregado: { 10: 1, 1: 1 },
  },
  {
    id: "VTA-EXAMPLE-02",
    cliente: {
      id: 5,
      nombre: "Maria",
      apellidos: "García",
      telefonos: [{ tipo: "Móvil", numero: "275-111-2222" }],
      direcciones: [],
    },
    items: [
      {
        productId: "PM",
        optionId: "PM",
        optionName: "Pierna y Muslo",
        quantity: 1.5,
        cost: 90.0,
        priceType: "publico",
        pricePerKg: 60,
        personalizations: {},
      },
      {
        productId: "PA",
        optionId: "manual",
        optionName: "Producto Adicional",
        quantity: 1,
        cost: 18.0,
        priceType: null,
        pricePerKg: null,
        personalizations: { descripcion: ["Cebolla"] },
      },
    ],
    total: 108.0,
    fechaCompletado: new Date(Date.now() - 20 * 60000).toISOString(),
    pagoCon: { 200: 1 },
    cambioEntregado: { 50: 1, 20: 2, 2: 1 },
  },
  {
    id: "VTA-EXAMPLE-03",
    cliente: {
      id: 6,
      nombre: "Juan",
      apellidos: "Perez",
      telefonos: [{ tipo: "Móvil", numero: "275-222-3333" }],
      direcciones: [],
    },
    items: [
      {
        productId: "POLLO-E",
        optionId: "POLLO-E",
        optionName: "Pollo Entero",
        quantity: 1,
        cost: 180.0,
        priceType: "publico",
        pricePerKg: 90,
        personalizations: { Procesamientos: ["Rostizar"] },
      },
    ],
    total: 180.0,
    fechaCompletado: new Date(Date.now() - 30 * 60000).toISOString(),
    pagoCon: { 200: 1 },
    cambioEntregado: { 20: 1 },
  },
  {
    id: "VTA-EXAMPLE-04",
    cliente: {
      id: 7,
      nombre: "Ana",
      alias: "Anita",
      telefonos: [{ tipo: "Móvil", numero: "275-444-5555" }],
      direcciones: [],
    },
    items: [
      {
        productId: "PECH",
        optionId: "PP-PECH",
        optionName: "Pulpa de Pechuga",
        quantity: 0.5,
        cost: 92.5,
        priceType: "publico",
        pricePerKg: 185,
        personalizations: { Procesamientos: ["Bistec"] },
      },
      {
        productId: "AL",
        optionId: "AL",
        optionName: "Ala",
        quantity: 1.0,
        cost: 100.0,
        priceType: "publico",
        pricePerKg: 100,
        personalizations: {},
      },
    ],
    total: 192.5,
    fechaCompletado: new Date(Date.now() - 35 * 60000).toISOString(),
    pagoCon: { 500: 1 },
    cambioEntregado: { 200: 1, 100: 1, 5: 1, 2: 1, 0.5: 1 },
  },
  {
    id: "VTA-EXAMPLE-05",
    cliente: {
      id: 8,
      nombre: "Luis",
      apellidos: "Gomez",
      telefonos: [{ tipo: "Móvil", numero: "275-555-6666" }],
      direcciones: [],
    },
    items: [
      {
        productId: "PM",
        optionId: "PM",
        optionName: "Pierna y Muslo",
        quantity: 2.0,
        cost: 120.0,
        priceType: "publico",
        pricePerKg: 60,
        personalizations: {},
      },
      {
        productId: "ENVIO",
        optionId: "express-chiautla",
        optionName: "D. Express Chiautla",
        quantity: 1,
        cost: 15.0,
        priceType: null,
        pricePerKg: null,
        personalizations: { descripcion: ["$15.00"] },
      },
    ],
    total: 135.0,
    fechaCompletado: new Date(Date.now() - 42 * 60000).toISOString(),
    pagoCon: { 100: 1, 50: 1 },
    cambioEntregado: { 10: 1, 5: 1 },
  },
  {
    id: "VTA-EXAMPLE-06",
    cliente: {
      id: 9,
      nombre: "Sofia",
      apellidos: "Martinez",
      telefonos: [{ tipo: "Móvil", numero: "275-666-7777" }],
      direcciones: [],
    },
    items: [
      {
        productId: "AL",
        optionId: "AL",
        optionName: "Ala",
        quantity: 0.5,
        cost: 50.0,
        priceType: "publico",
        pricePerKg: 100,
        personalizations: { Procesamientos: ["Adobada"] },
      },
    ],
    total: 50.0,
    fechaCompletado: new Date(Date.now() - 50 * 60000).toISOString(),
    pagoCon: { 50: 1 },
    cambioEntregado: {},
  },
  {
    id: "VTA-EXAMPLE-07",
    cliente: {
      id: 4,
      nombre: "Pedro",
      alias: "Peter",
      telefonos: [{ tipo: "Móvil", numero: "275-333-4444" }],
      direcciones: [],
    },
    items: [
      {
        productId: "POLLO-E",
        optionId: "POLLO-E",
        optionName: "Pollo Entero",
        quantity: 1,
        cost: 180.0,
        priceType: "publico",
        pricePerKg: 90,
        personalizations: { Procesamientos: ["En piezas"] },
      },
      {
        productId: "PA",
        optionId: "manual",
        optionName: "Producto Adicional",
        quantity: 1,
        cost: 30.0,
        priceType: null,
        pricePerKg: null,
        personalizations: { descripcion: ["Chiles secos"] },
      },
    ],
    total: 210.0,
    fechaCompletado: new Date(Date.now() - 55 * 60000).toISOString(),
    pagoCon: { 500: 1 },
    cambioEntregado: { 200: 1, 50: 1, 20: 2 },
  },
  {
    id: "VTA-EXAMPLE-08",
    cliente: {
      id: 5,
      nombre: "Maria",
      apellidos: "García",
      telefonos: [{ tipo: "Móvil", numero: "275-111-2222" }],
      direcciones: [],
    },
    items: [
      {
        productId: "PECH",
        optionId: "PP-PECH",
        optionName: "Pulpa de Pechuga",
        quantity: 1.0,
        cost: 185.0,
        priceType: "publico",
        pricePerKg: 185,
        personalizations: {},
      },
    ],
    total: 185.0,
    fechaCompletado: new Date(Date.now() - 62 * 60000).toISOString(),
    pagoCon: { 200: 1 },
    cambioEntregado: { 10: 1, 5: 1 },
  },
  {
    id: "VTA-EXAMPLE-09",
    cliente: {
      id: 10,
      nombre: "Carlos",
      apellidos: "Sanchez",
      telefonos: [{ tipo: "Móvil", numero: "275-888-9999" }],
      direcciones: [],
    },
    items: [
      {
        productId: "AL",
        optionId: "AL",
        optionName: "Ala",
        quantity: 1.0,
        cost: 100.0,
        priceType: "publico",
        pricePerKg: 100,
        personalizations: {},
      },
      {
        productId: "PA",
        optionId: "manual",
        optionName: "Producto Adicional",
        quantity: 1,
        cost: 25.0,
        priceType: null,
        pricePerKg: null,
        personalizations: { descripcion: ["Jitomates"] },
      },
    ],
    total: 125.0,
    fechaCompletado: new Date(Date.now() - 70 * 60000).toISOString(),
    pagoCon: { 100: 1, 20: 1, 5: 1 },
    cambioEntregado: {},
  },
  {
    id: "VTA-EXAMPLE-10",
    cliente: {
      id: 7,
      nombre: "Ana",
      alias: "Anita",
      telefonos: [{ tipo: "Móvil", numero: "275-444-5555" }],
      direcciones: [],
    },
    items: [
      {
        productId: "PM",
        optionId: "PM",
        optionName: "Pierna y Muslo",
        quantity: 1.0,
        cost: 60.0,
        priceType: "publico",
        pricePerKg: 60,
        personalizations: {},
      },
      {
        productId: "ENVIO",
        optionId: "express-chiautla",
        optionName: "D. Express Chiautla",
        quantity: 1,
        cost: 15.0,
        priceType: null,
        pricePerKg: null,
        personalizations: { descripcion: ["$15.00"] },
      },
    ],
    total: 75.0,
    fechaCompletado: new Date(Date.now() - 75 * 60000).toISOString(),
    pagoCon: { 100: 1 },
    cambioEntregado: { 20: 1, 5: 1 },
  },
  {
    id: "VTA-EXAMPLE-11",
    cliente: {
      id: 8,
      nombre: "Luis",
      apellidos: "Gomez",
      telefonos: [{ tipo: "Móvil", numero: "275-555-6666" }],
      direcciones: [],
    },
    items: [
      {
        productId: "POLLO-E",
        optionId: "POLLO-E",
        optionName: "Pollo Entero",
        quantity: 1,
        cost: 180.0,
        priceType: "publico",
        pricePerKg: 90,
        personalizations: {},
      },
      {
        productId: "PECH",
        optionId: "PP-PECH",
        optionName: "Pulpa de Pechuga",
        quantity: 0.5,
        cost: 92.5,
        priceType: "publico",
        pricePerKg: 185,
        personalizations: {},
      },
    ],
    total: 272.5,
    fechaCompletado: new Date(Date.now() - 85 * 60000).toISOString(),
    pagoCon: { 200: 1, 100: 1 },
    cambioEntregado: { 20: 1, 5: 1, 2: 1, 0.5: 1 },
  },
  {
    id: "VTA-EXAMPLE-12",
    cliente: {
      id: 9,
      nombre: "Sofia",
      apellidos: "Martinez",
      telefonos: [{ tipo: "Móvil", numero: "275-666-7777" }],
      direcciones: [],
    },
    items: [
      {
        productId: "AL",
        optionId: "AL",
        optionName: "Ala",
        quantity: 0.8,
        cost: 80.0,
        priceType: "publico",
        pricePerKg: 100,
        personalizations: {},
      },
      {
        productId: "PM",
        optionId: "PM",
        optionName: "Pierna y Muslo",
        quantity: 1.2,
        cost: 72.0,
        priceType: "publico",
        pricePerKg: 60,
        personalizations: {},
      },
    ],
    total: 152.0,
    fechaCompletado: new Date(Date.now() - 93 * 60000).toISOString(),
    pagoCon: { 200: 1 },
    cambioEntregado: { 20: 2, 5: 1, 2: 1, 1: 1 },
  },
  {
    id: "VTA-EXAMPLE-13",
    cliente: {
      id: 4,
      nombre: "Pedro",
      alias: "Peter",
      telefonos: [{ tipo: "Móvil", numero: "275-333-4444" }],
      direcciones: [],
    },
    items: [
      {
        productId: "PA",
        optionId: "manual",
        optionName: "Producto Adicional",
        quantity: 2,
        cost: 50.0,
        priceType: null,
        pricePerKg: null,
        personalizations: { descripcion: ["Jitomates (2kg)"] },
      },
    ],
    total: 50.0,
    fechaCompletado: new Date(Date.now() - 100 * 60000).toISOString(),
    pagoCon: { 50: 1 },
    cambioEntregado: {},
  },
  {
    id: "VTA-EXAMPLE-14",
    cliente: {
      id: 5,
      nombre: "Maria",
      apellidos: "García",
      telefonos: [{ tipo: "Móvil", numero: "275-111-2222" }],
      direcciones: [],
    },
    items: [
      {
        productId: "POLLO-E",
        optionId: "POLLO-E",
        optionName: "Pollo Entero",
        quantity: 1,
        cost: 180.0,
        priceType: "publico",
        pricePerKg: 90,
        personalizations: {},
      },
      {
        productId: "ENVIO",
        optionId: "express-chiautla",
        optionName: "D. Express Chiautla",
        quantity: 1,
        cost: 15.0,
        priceType: null,
        pricePerKg: null,
        personalizations: { descripcion: ["$15.00"] },
      },
    ],
    total: 195.0,
    fechaCompletado: new Date(Date.now() - 110 * 60000).toISOString(),
    pagoCon: { 200: 1 },
    cambioEntregado: { 5: 1 },
  },
  {
    id: "VTA-EXAMPLE-15",
    cliente: {
      id: 6,
      nombre: "Juan",
      apellidos: "Perez",
      telefonos: [{ tipo: "Móvil", numero: "275-222-3333" }],
      direcciones: [],
    },
    items: [
      {
        productId: "PECH",
        optionId: "PP-PECH",
        optionName: "Pulpa de Pechuga",
        quantity: 0.5,
        cost: 92.5,
        priceType: "publico",
        pricePerKg: 185,
        personalizations: {},
      },
      {
        productId: "PA",
        optionId: "manual",
        optionName: "Producto Adicional",
        quantity: 1,
        cost: 25.0,
        priceType: null,
        pricePerKg: null,
        personalizations: { descripcion: ["Jitomates"] },
      },
      {
        productId: "ENVIO",
        optionId: "express-chiautla",
        optionName: "D. Express Chiautla",
        quantity: 1,
        cost: 15.0,
        priceType: null,
        pricePerKg: null,
        personalizations: { descripcion: ["$15.00"] },
      },
    ],
    total: 132.5,
    fechaCompletado: new Date(Date.now() - 120 * 60000).toISOString(),
    pagoCon: { 100: 1, 50: 1 },
    cambioEntregado: { 10: 1, 5: 1, 2: 1, 0.5: 1 },
  },
];
